theme: jekyll-theme-cayman

title: getworking

name: Kyle Evans

description: Networking, Infrastructure, and DevOps

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

footer-links:
  github: kylebeevans
  linkedin:
  twitter: kylebe
  
url: http://getworking.org

permalink: /:title/

gems:
  - jekyll-sitemap
  
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME