theme: jekyll-theme-cayman

title: Kyle Evans

name: Kyle Evans

author: Kyle Evans

description: " "

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

footer-links:
  github: kylebeevans
  linkedin:
  twitter: bekyle

url: http://www.getworking.org

permalink: /:title/

gems:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
